apiVersion: v1
kind: Service
metadata:
  name: backend-dpl
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http-janus
  selector:
    app: backend
  sessionAffinity: None
  type: ClusterIP